### ISSUE TITLE
plz images

### ISSUE THREAD

**Issue by mynameismhmd** [mo7amedaliEbaid/Ecommerce-Flutter#1]

**Comment by mo7amedaliEbaid** [comment]
![account](https://github.com/mo7amedaliEbaid/Ecommerce-Flutter/assets/131966482/9b3412f7-71fa-4d38-8a58-db1f52118f88)
https://github.com/mo7amedaliEbaid/Ecommerce-Flutter/tree/master/ecommerce/screen_shots
I added some screen_shots 
@mynameismhmd
